### ISSUE TITLE
starttls handshake: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by RushHour2k5** [xmppo/go-xmpp#111]
Not sure if anyone would be able to help here however it appears that the issue might be related to this plugin. I'm trying to configure the https://github.com/skburgart/go-vacbot plugin which appears to use the go-xmpp scripts as it is shown under the vendor files however when it attempts to connect to the Ecovacs XMPP server at msg-na.ecouser.net:5223 it fails with "starttls handshake: x509: certificate has expired or is not yet valid". I have downloaded the repository and updated the vendor files with the latest copy of go-xmpp and rebuilt the plugin as an executable file using https://github.com/MnrGreg/homebridge-ecovacs-deebot however it still fails. I cannot for the life of me figure out how to ignore the TLS for XMPP. I went back to the original plugin the GoLang script is based off of which is https://github.com/wpietri/sucks and an issue at https://github.com/wpietri/sucks/issues/62 makes reference to removing pyasn1 and pyasn1-modules from Python as a workaround but cannot find how to do a similar process for these GoLang scripts.

Existing issues are open under the plugins at https://github.com/skburgart/go-vacbot/issues/3 and at https://github.com/MnrGreg/homebridge-ecovacs-deebot/issues/1.

**Comment by mdosch** [comment]
You can set `InsecureSkipVerify` in [tls.Config](https://pkg.go.dev/crypto/tls#Config) but I would rather fix the server to provide valid certs.
