### ISSUE TITLE
Empty chat record on Recv

### ISSUE THREAD

**Issue by gatlin** [xmppo/go-xmpp#13]
I am using a slightly modified version of your example code (go-iconv doesn't work on my version of Mac OS X but github.com/djimenez/iconv-go does work => my UTF8 conversion functions are slightly different). I can send messages just fine and I can produce some kind of output every time I receive one but the chat record itself is empty. I verified this with

```
go func() {
    for {
        chat, err := talk.Recv()
        if err != nil {
            log.Fatal(err)
            fmt.Printf("Trouble receiving chat\n")
        }
        fmt.Printf("%v\n", chat)
    }
}()
```

And I receive `{ }` for each message. Connecting to google talk servers.

**Comment by gatlin** [comment]
@mdosch I will reinstall Go and let you know asap!

**Comment by mdosch** [comment]
Just now I realized that this issue was about using "google talk", as "google talk" went to where all google chat services go long ago I'm going to close this issue.
