### ISSUE TITLE
Broken URL in oob message.

### ISSUE THREAD

**Issue by mdosch** [xmppo/go-xmpp#132]
When sending a file via http-upload you usually send the URL in oob and in the message body. But it seems the Ooburl is getting altered (compare oob URL to URL in body):

```
<body>https://upload.example.org:5281/upload/PBOIXpKDzGecqJzo/&amp;%25%3c%3e.txt</body><x xmlns='jabber:x:oob'><url>https://upload.example.org:5281/upload/PBOIXpKDzGecqJzo/&amp;%3c%!e(MISSING).txt</url></x>
```

**Comment by mdosch** [comment]
Might be a similar issue like https://github.com/FluuxIO/go-xmpp/issues/113

**Comment by Zash** [comment]
Most likely here:

https://github.com/mattn/go-xmpp/blob/3871461df959effa2649e18669dc32a5221a7efa/xmpp.go#L826-L837

**Comment by mdosch** [comment]
I tested with some strings that made problems before (e.g. https://da.wikipedia.org/wiki/J%C3%A6vnd%C3%B8gn) and could not reproduce the issue anymore.
