### ISSUE TITLE
Close Recv() before closing connection

### ISSUE THREAD

**Issue by mdosch** [xmppo/go-xmpp#154]
Dear mattn,

I have a goroutine where I run Recv() to receive stanzas and e.g. reply to IQs.
Sometimes I get the following output when closing my program:

> 2023/07/28 14:11:17 read tcp [CLIENT_IP]:58128->[SERVER_IP]:5223: use of closed network connection

It would be nice if go-xmpp would stop reading on the connection via Recv() function before closing the connection on Close() or would provide a way to cancel Recv() (if that's possible).

Best regards,
Martin

**Comment by ridhodo** [comment]
i also face this issue

**Comment by cevin** [comment]
me too

**Comment by mdosch** [comment]
I made some changes and to the library and now this seems to be no more the case with the current development version.
@ridhodo and @cevin can you confirm?
