### ISSUE TITLE
New release build?

### ISSUE THREAD

**Issue by Neustradamus** [xmppo/go-xmpp#166]
I think it is time to create a new release build with all recent improvements since the first "recent" tag:
- https://github.com/xmppo/go-xmpp/tags

But what version?

The @mattn (Yasuhiro Matsumoto) project exists since 2011-02-28 based on @rsc (Russ Cox) work:
- https://github.com/rsc/rsc/tree/master/xmpp
- https://github.com/rsc/rsc/commits/master/xmpp

There is an another and old go-xmpp project:
- https://github.com/FluuxIO/go-xmpp
- https://pkg.go.dev/gosrc.io/xmpp

The latest version is 0.5.1 (2020-03-23):
- https://github.com/FluuxIO/go-xmpp/releases

Badly, currently several people mix...

**Comment by mdosch** [comment]
I don't understand what those other libraries have to do with the versioning of this library.
@mattn  Before tagging a new release we should consider removing DIGEST-MD5 which is obsolete for a long time: https://datatracker.ietf.org/doc/html/rfc6331
I'm also not aware of DIGEST-MD5 being used anywhere in the wild anymore.

**Comment by mdosch** [comment]
Maybe also decide on #172 before tagging.

**Comment by mdosch** [comment]
@mattn What do you think about tagging the current status as 0.1.0? As SCRAM (including the PLUS variants) is supported now and also XEP-0474 is working it might be useful to get this out to users. As there exists a tag 0.0.1 right now this tag will be used unless the use of master is explicitly enforced by `go get github.com/xmppo/go-xmpp@master`.

**Comment by Neustradamus** [comment]
@ivucica: Do you know this project? :)
