### ISSUE TITLE
xmppo/go-xmpp or mattn/go-xmpp

### ISSUE THREAD

**Issue by mdosch** [xmppo/go-xmpp#172]
Dear @mattn 

as the project moved from github.com/mattn/go-xmpp to github.com/xmppo/go-xmpp I wonder whether you also want to use the latter as import path right now.

This would require deleting the old `go.mod` file and invoking these two commands:

```
go mod init github.com/xmppo/go-xmpp
go mod tidy
```

**Comment by mattn** [comment]
Yeah, please do.
