### ISSUE TITLE
XEP-0440: SASL Channel-Binding Type Capability

### ISSUE THREAD

**Issue by Neustradamus** [xmppo/go-xmpp#191]
Dear @go-xmpp team, @mdosch,

Can you add "XEP-0440: SASL Channel-Binding Type Capability" support?
- https://xmpp.org/extensions/xep-0440.html

Thanks in advance.

**Comment by mdosch** [comment]
Already supported.

**Comment by Neustradamus** [comment]
@mdosch: Badly I do not find in the code :/
- https://github.com/search?q=repo%3Axmppo%2Fgo-xmpp+0440&type=code

Can you add details in code?

**Comment by mdosch** [comment]
You'll find it if you search for the namespace.
Maybe you could contribute some documentation when working on #114 and 
#115.

Am 08.11.2024 12:48, schrieb Neustradamus:

**Comment by Neustradamus** [comment]
@mdosch: The .doap file is really important :)
Same for go-sendxmpp

**Comment by mdosch** [comment]
@Neustradamus see #193, #114  and #115.
