### ISSUE TITLE
Server waits forever on receiving next(c.p)

### ISSUE THREAD

**Issue by boopathi** [xmppo/go-xmpp#28]
https://github.com/mattn/go-xmpp/blob/8a80c8abe319ccc0e61b63684158bffd1a61ca5a/xmpp.go#L315

I placed a few printfs and the server seems to wait on this line forever. No errors thrown either. When I turn debug ON, I was able to see the <success> tag. 

```
boopathi example(master)> go run example.go -server localhost:5222 -username test@boopathi -password testtest -notls -debug
<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="boopathi" id="fc88ef3d" xml:lang="en" version="1.0">
SE =  {{http://etherx.jabber.org/streams stream} [{{xmlns stream} http://etherx.jabber.org/streams} {{ xmlns} jabber:client} {{ from} boopathi} {{ id} fc88ef3d} {{http://www.w3.org/XML/1998/namespace lang} en} {{ version} 1.0}]}
<stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>DIGEST-MD5</mechanism><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS</mechanism><mechanism>CRAM-MD5</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><auth xmlns="http://jabber.org/features/iq-auth"/><register xmlns="http://jabber.org/features/iq-register"/></stream:features>
Mechanism =  DIGEST-MD5
<challenge xmlns="urn:ietf:params:xml:ns:xmpp-sasl">cmVhbG09ImJvb3BhdGhpIixub25jZT0iOXM3dTVMYjByd240VFB6TzBJbUJOMjhXN1dyaHAwT1NzamVtbUFhMyIscW9wPSJhdXRoIixjaGFyc2V0PXV0Zi04LGFsZ29yaXRobT1tZDUtc2Vzcw==</challenge>
<success xmlns="urn:ietf:params:xml:ns:xmpp-sasl">cnNwYXV0aD01MTI1YmIwY2JiNzMxMWMyODlkZmIwMTY3Yzc4Nzc2Yg==</success>
Waiting for next message
</stream:stream>
```

**Comment by clone1018** [comment]
I'm having the same issue, did you ever figure it out @boopathi ?

**Comment by clone1018** [comment]
cc @mattn

**Comment by mattn** [comment]
What the server do you use?

**Comment by clone1018** [comment]
I'm trying to use it with OpenFire

**Comment by clone1018** [comment]
This is my output 

```
<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="127.0.0.1" id="REDACTED" xml:lang="en" version="1.0">
<stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>DIGEST-MD5</mechanism><mechanism>PLAIN</mechanism><mechanism>CRAM-MD5</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><auth xmlns="http://jabber.org/features/iq-auth"/></stream:features>
<proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="127.0.0.1" id="REDACTED" xml:lang="en" version="1.0"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>DIGEST-MD5</mechanism><mechanism>PLAIN</mechanism><mechanism>CRAM-MD5</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><auth xmlns="http://jabber.org/features/iq-auth"/></stream:features>
<challenge xmlns="urn:ietf:params:xml:ns:xmpp-sasl">REDACTED</challenge>
<success xmlns="urn:ietf:params:xml:ns:xmpp-sasl">REDACTED</success>
</stream:stream>
```

Then everything stops and it never gets to the go function to read the talk.Recv

**Comment by dullgiulio** [comment]
Can confirm this, I made some changes in my fork[1], but I am not ready to PR yet.

[1] https://github.com/dullgiulio/go-xmpp/commit/07352ce6dc735e200c220a747ab5af746aebc0ce

**Comment by martinhpedersen** [comment]
Is anyone working on this bug?

It looks to me like the io.EOF error from [func (*xml.Decoder) Token](https://golang.org/pkg/encoding/xml/#Decoder.Token) (indicating end of XML stream) is ignored. It should probably trigger connection re-initiation, or at least cause `c.Recv` to return io.EOF so it can be handled outside the package.

https://github.com/mattn/go-xmpp/blob/8a80c8abe319ccc0e61b63684158bffd1a61ca5a/xmpp.go#L540

**Comment by dullgiulio** [comment]
Sorry, we stopped using OpenFire and I can't reproduce this any longer.

But wouldn't that line end up in panic(unreacheable) is an EOF is received there?

**Comment by martinhpedersen** [comment]
https://play.golang.org/p/9FiXqI8F0b

I'm afraid not. Since the type switch below don't catch it (the token t is nil), it will simply continue looping forever.

@mattn - Any interest in accepting a pull request that would expose this error to the c.Recv() caller? I can't understand how ignoring that io.EOF could lead to anything but an unrecoverable failure, but I may of course be missing something here.

@dullgiulio - Out of curiosity, do you know if OpenFire implements [XMPP Ping](https://xmpp.org/extensions/xep-0199.html)? After enabling this on our ejabberd instance, it looks like we're getting io.UnexpectedEOF instead of a non-responsive Recv() call when the connection is broken.

**Comment by mattn** [comment]
Your patch seems good for me.

**Comment by martinhpedersen** [comment]
I'm sorry. I was looking at (and linking to) an old blob that.

Commit 9dd92e124738bea45d60514e3aa597d7f999d907 changed the behaviour of this function, so my playground example is no longer valid.

Although the patched version behaves as I suggested (https://play.golang.org/p/FAP7Wa8hll), I still suggest that we remove the `err != io.EOF` statement. It appears misleading, and may still cause issues (depending on the xml package's behaviour).

I'm sending you a PR in a couple of minutes.
