### ISSUE TITLE
Problem with TLSCertVerify ?

### ISSUE THREAD

**Issue by jadjay** [xmppo/go-xmpp#78]
Is there option to not check TLS cert in case of SSL or STARTTLS ?

**Comment by mdosch** [comment]
@jadjay as long as you don't tell the library to not check the certs by setting SkipInsecureVerify in tls.Config TLS certs are automatically checked.

See for example this test with go-sendxmpp (which is using this library):

```
date|./go-sendxmpp -u test@self-signed.badxmpp.eu -p test test@example.com
2024/02/25 13:01:26 failed to connect to server: starttls handshake: tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-02-25T13:01:26+01:00 is after 2023-12-25T23:39:44Z
```
