### ISSUE TITLE
xmpp.NewClient() is not thread-safe

### ISSUE THREAD

**Issue by froodian** [xmppo/go-xmpp#85]
Calling xmpp.NewClient() from more than one goroutine can cause a data race (exposed by the `-race` flag for `go test`)

The culprit is at https://github.com/mattn/go-xmpp/blob/master/xmpp.go#L193, that should create a new config based on the shared DefaultConfig variable instead of modifying DefaultConfig.

This can currently be worked-around by using opts.NewClient() instead (and providing a TLSConfig to opts), but it would be good to fix the race as well.

**Comment by mattn** [comment]
https://github.com/mattn/go-xmpp/commit/906d9d747d2b4c59e60104678b62e464dd1623cf

This change doesn't fix thread-safe. But this may fix your issue.

**Comment by mdosch** [comment]
As @mattn pushed a potential fix almost 7 years ago and here was no feedback I'm going to close this.
