### ISSUE TITLE
Getting EOF with correct credentials.

### ISSUE THREAD

**Issue by jimmiebtlr** [xmppo/go-xmpp#89]
Using a node library I can connect to an olark xmpp client.
With golang and the same credentials I get 

```
 (*errors.errorString)(0xc42003c060)(EOF)
```
The options I'm using are 
```
	opts := xmpp.Options{
		User:     "user@olark.com",
		Password: "password",
		NoTLS:    true,
		InsecureAllowUnencryptedAuth: true,
	}
```

I've also tried without the NoTLS and InsecureAllowUnencryptedAuth options.

**Comment by mattn** [comment]
Where is the function return the EOF?

**Comment by jimmiebtlr** [comment]
The EOF is returned on the NewClient call

**Comment by mattn** [comment]
Do you use proxy?

**Comment by jimmiebtlr** [comment]
No

**Comment by mattn** [comment]
Hmm, As far as I see the code, EOF return if close tag is missing. What XMPP server did you try?

**Comment by mdosch** [comment]
@jimmiebtlr I am going through some old issues in this repo. A lot has changed in >6 years, so is this still an issue?

**Comment by mdosch** [comment]
There was no reply whether this is still an issue for half a year, therefore I'm going to close this issue.
